version: '3'
networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16
services:
  alm-ansible-rm-db:
     hostname: ansible-rm-db
     container_name: ansible-rm-db
     image: cassandra:3.10
     ports:
       - "9042:9042"
       - "9160:9160"
     volumes:
       - "./var_alm_ansible_rm/cassandra:/var/lib/cassandra/data"
     environment:
       # important: broadcast address must be set to the Docker hostname
       - CASSANDRA_BROADCAST_ADDRESS=alm-ansible-rm-db
       - CASSANDRA_CLUSTER_NAME=alm-ansible-rm-cluster
       - CASSANDRA_SEEDS=alm-ansible-rm-db
       - CASSANDRA_REMOTE_CONNECTION=true
       - CASSANDRA_START_RPC=true
  alm-ansible-rm:
     hostname: ansible-rm
     container_name: ansible-rm
     build:
       context: ./ansible-adaptor
       dockerfile: Dockerfile
     image: arm:1.3.7
     ports:
       - "8080:8080"
     volumes:
       - "./var_alm_ansible_rm/driver:/var/alm_ansible_rm"
       - "./ansible-adaptor:/usr/src/app"
     environment:
       - LOG_LEVEL=DEBUG
       - LOG_FOLDER=/var/alm_ansible_rm/logs
       - OS_CLIENT_CONFIG_FILE=/var/alm_ansible_rm/clouds/clouds.yaml
       - KAFKA_URL=172.16.14.7:30541
       - kafka_replicationFactor=1
     extra_hosts:
       - "kafka:172.16.14.7"
     depends_on:
       - alm-ansible-rm-db
