driver:
  name: ansible-rm
  version: 0.1
  supportedApiVersions:
    - "1.0"
  supportedFeatures:
    AsynchronousTransitionResponses: true
  properties:
    - responseKafkaConnectionUrl: "kafka:9092"
    - responseKafkaTopicName: "ansible-rm"
ansible:
  resource_dir: "/var/alm_ansible_rm/resources"
  keys_dir: "/var/alm_ansible_rm/keys"
cassandra:
  uri: alm-ansible-rm-db
#  uri: 192.168.99.100
  ttl: 86400
