name: osslm-ansible-resource-manager
version: 1.4.0
appVersion: 1.4.0
apiVersion: v1
description: A Helm chart for the osslm-ansible-resource-manager
# maintainers:
#- name:
#  email:
keywords:
- OSS
- LM
- OSSLM
- Resource Manager
- Ansible
- IBM
engine: gotpl
